server:
  port: 8080
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      default-filters: #filtro por defecto de todos los requests del query
        - name: LogFilter
      routes:
        - id: clientConsumer
          uri:  lb://musica
          #uri: http://localhost:8065
          predicates:
            - Path=/canciones/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
            - LogFilter=Hola este es el mensaje que tal como tu estas, usuario, AyeLaMasKpa

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

